import { StyleSheet } from "react-native";

export const colors = {
  background: "#fbfaf7",
  surface: "#ffffff",
  ink: "#252326",
  muted: "#716b72",
  faint: "#eae0d1", // #ece7df
  accent: "#7d4f63",
  accentSoft: "#f4edf0",
  success: "#2f684f",
  successSoft: "#edf7f1",
  placeholder: "#9b949d",
};

export const fonts = {
  app: 'Inter, "Helvetica Neue", "Segoe UI", Roboto, Arial, sans-serif',
};

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.background,
  },
  appShell: {
    flex: 1,
    backgroundColor: colors.background,
  },
  topBar: {
    width: "100%",
    maxWidth: 760,
    alignSelf: "center",
    paddingHorizontal: 24,
    paddingTop: 18,
    paddingBottom: 14,
    backgroundColor: colors.background,
    borderBottomWidth: 1,
    borderBottomColor: colors.faint,
    gap: 12,
  },
  brandRow: {
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 10,
    flexWrap: "wrap",
  },
  logoLockup: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  logoIcon: {
    width: 27,
    height: 27,
  },
  logo: {
    fontFamily: fonts.app,
    color: colors.ink,
    fontSize: 27,
    lineHeight: 32,
    fontWeight: "600",
    letterSpacing: -0.2,
  },
  tagline: {
    color: colors.muted,
    fontSize: 13,
    lineHeight: 18,
  },
  accountLine: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 8,
  },
  accountBadgeRow: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    maxWidth: "100%",
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.faint,
  },
  personalityLabel: {
    fontFamily: fonts.app,
    flexShrink: 1,
    color: colors.muted,
    fontSize: 12,
    lineHeight: 17,
    fontStyle: "italic",
  },
  accountEmail: {
    fontFamily: fonts.app,
    color: colors.muted,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "500",
  },
  nav: {
    flexDirection: "row",
    gap: 6,
  },
  navButton: {
    flex: 1,
    borderRadius: 999,
    paddingVertical: 10,
    alignItems: "center",
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.faint,
  },
  navButtonActive: {
    backgroundColor: colors.accentSoft,
    borderColor: colors.accent,
  },
  navIconButton: {
    flexGrow: 0,
    flexShrink: 0,
    width: 46,
    minWidth: 46,
    minHeight: 40,
    paddingHorizontal: 0,
    justifyContent: "center",
  },
  navIcon: {
    width: 18,
    height: 18,
  },
  navText: {
    fontFamily: fonts.app,
    color: colors.muted,
    fontSize: 13,
    fontWeight: "500",
  },
  navTextActive: {
    color: colors.accent,
  },
  content: {
    flex: 1,
  },
  contentInner: {
    width: "100%",
    maxWidth: 760,
    alignSelf: "center",
    paddingHorizontal: 24,
    paddingTop: 16,
    paddingBottom: 48,
  },
  screen: {
    gap: 20,
  },
  screenHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 12,
  },
  screenHeaderCopy: {
    flex: 1,
    flexDirection: "row",
    alignItems: "baseline",
    flexWrap: "wrap",
    columnGap: 12,
    rowGap: 4,
  },
  screenTitle: {
    fontFamily: fonts.app,
    color: colors.ink,
    fontSize: 22,
    lineHeight: 28,
    fontWeight: "600",
    letterSpacing: 0,
  },
  screenBody: {
    fontFamily: fonts.app,
    flexShrink: 1,
    color: colors.muted,
    fontSize: 13,
    lineHeight: 21,
    maxWidth: 560,
  },
  errorText: {
    fontFamily: fonts.app,
    color: colors.accent,
    fontSize: 13,
    lineHeight: 20,
  },
  successText: {
    fontFamily: fonts.app,
    color: colors.success,
    fontSize: 13,
    lineHeight: 20,
  },
  disclaimerBanner: {
    gap: 4,
    padding: 14,
    borderRadius: 12,
    backgroundColor: colors.accentSoft,
    borderWidth: 1,
    borderColor: colors.faint,
  },
  disclaimerTitle: {
    fontFamily: fonts.app,
    color: colors.ink,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "600",
  },
  disclaimerText: {
    fontFamily: fonts.app,
    color: colors.muted,
    fontSize: 12,
    lineHeight: 18,
  },
  helperText: {
    fontFamily: fonts.app,
    color: colors.muted,
    fontSize: 12,
    lineHeight: 17,
  },
  inlineLink: {
    fontFamily: fonts.app,
    color: colors.accent,
    fontSize: 13,
    lineHeight: 20,
    fontWeight: "600",
    textDecorationLine: "underline",
  },
  authShell: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    padding: 24,
    backgroundColor: colors.background,
  },
  authPanel: {
    width: "100%",
    maxWidth: 430,
    gap: 12,
    padding: 24,
    borderRadius: 16,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.faint,
  },
  authTitle: {
    fontFamily: fonts.app,
    color: colors.ink,
    fontSize: 22,
    lineHeight: 28,
    fontWeight: "600",
  },
  authForm: {
    gap: 12,
    marginTop: 8,
  },
  inputGroup: {
    gap: 6,
  },
  inputLabel: {
    fontFamily: fonts.app,
    color: colors.ink,
    fontSize: 13,
    fontWeight: "500",
  },
  textInput: {
    fontFamily: fonts.app,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.faint,
    backgroundColor: colors.background,
    color: colors.ink,
    fontSize: 15,
    paddingHorizontal: 12,
    paddingVertical: 11,
  },
  authSwitch: {
    alignSelf: "center",
    paddingVertical: 6,
  },
  checkboxRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
    paddingVertical: 2,
  },
  checkboxBox: {
    width: 20,
    height: 20,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 5,
    borderWidth: 1,
    borderColor: colors.faint,
    backgroundColor: colors.background,
  },
  checkboxBoxChecked: {
    borderColor: colors.accent,
    backgroundColor: colors.accent,
  },
  checkboxMark: {
    fontFamily: fonts.app,
    color: colors.surface,
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "600",
  },
  checkboxLabel: {
    fontFamily: fonts.app,
    flex: 1,
    color: colors.muted,
    fontSize: 13,
    lineHeight: 20,
  },
  legalConsentText: {
    fontFamily: fonts.app,
    color: colors.muted,
    fontSize: 12,
    lineHeight: 18,
  },
  onboardingShell: {
    flex: 1,
    width: "100%",
    maxWidth: 760,
    alignSelf: "center",
    paddingHorizontal: 24,
    paddingTop: 18,
    paddingBottom: 48,
    backgroundColor: colors.background,
  },
  onboardingHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    flexWrap: "wrap",
    gap: 12,
    paddingBottom: 16,
    marginBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: colors.faint,
  },
  onboardingScroll: {
    flex: 1,
  },
  onboardingContent: {
    gap: 20,
    paddingBottom: 48,
  },
  section: {
    padding: 20,
    borderRadius: 16,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.faint,
  },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 12,
  },
  sectionHeaderCopy: {
    flex: 1,
    flexDirection: "row",
    alignItems: "baseline",
    flexWrap: "wrap",
    columnGap: 12,
    rowGap: 4,
  },
  sectionTitle: {
    fontFamily: fonts.app,
    color: colors.ink,
    fontSize: 18,
    lineHeight: 24,
    fontWeight: "600",
  },
  sectionSubtitle: {
    fontFamily: fonts.app,
    color: colors.muted,
    fontSize: 13,
    lineHeight: 20,
    maxWidth: 560,
  },
  sectionContent: {
    marginTop: 16,
  },
  settingsActions: {
    marginTop: 16,
    marginBottom: 12,
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 10,
  },
  backActionRow: {
    alignSelf: "stretch",
    alignItems: "flex-end",
  },
  legalLinkRow: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 10,
  },
  legalLinkPill: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.faint,
    paddingHorizontal: 10,
    paddingVertical: 7,
    backgroundColor: colors.background,
  },
  legalLinkPillActive: {
    borderColor: colors.accent,
    backgroundColor: colors.accentSoft,
  },
  legalLinkPillText: {
    fontFamily: fonts.app,
    color: colors.muted,
    fontSize: 13,
    fontWeight: "500",
  },
  legalLinkPillTextActive: {
    color: colors.accent,
  },
  legalCompactList: {
    gap: 14,
  },
  legalCompactRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
  },
  legalCompactCopy: {
    flex: 1,
    gap: 5,
  },
  legalCompactTitle: {
    fontFamily: fonts.app,
    color: colors.ink,
    fontSize: 14,
    lineHeight: 21,
    fontWeight: "600",
  },
  legalParagraph: {
    fontFamily: fonts.app,
    color: colors.muted,
    fontSize: 13,
    lineHeight: 19,
  },
  instructionsList: {
    marginTop: 16,
    gap: 10,
  },
  instructionsRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
  },
  instructionsNumber: {
    fontFamily: fonts.app,
    minWidth: 20,
    color: colors.accent,
    fontSize: 14,
    lineHeight: 21,
    fontWeight: "600",
  },
  instructionsText: {
    fontFamily: fonts.app,
    flex: 1,
    color: colors.muted,
    fontSize: 14,
    lineHeight: 21,
  },
  developerCredit: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  developerLogo: {
    width: 24,
    height: 27,
  },
  developerCreditCopy: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    columnGap: 6,
    rowGap: 4,
  },
  developerCreditText: {
    fontFamily: fonts.app,
    flexShrink: 1,
    color: colors.muted,
    fontSize: 12,
    lineHeight: 17,
  },
  developerCreditPill: {
    fontFamily: fonts.app,
    overflow: "hidden",
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 3,
    backgroundColor: "#e7f6df",
    color: "#386b35",
    fontSize: 12,
    lineHeight: 17,
    fontWeight: "600",
    textDecorationLine: "underline",
  },
  emptyState: {
    padding: 22,
    borderRadius: 16,
    backgroundColor: colors.accentSoft,
    borderWidth: 1,
    borderColor: colors.faint,
  },
  emptyStateCopy: {
    gap: 6,
  },
  emptyStateTitle: {
    fontFamily: fonts.app,
    color: colors.ink,
    fontSize: 17,
    lineHeight: 23,
    fontWeight: "600",
  },
  emptyStateQuote: {
    fontFamily: fonts.app,
    color: colors.muted,
    fontSize: 13,
    lineHeight: 20,
  },
  emptyStateQuoteText: {
    fontStyle: "italic",
  },
  list: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  bookRow: {
    borderRadius: 16,
    padding: 18,
    width: "100%",
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.faint,
  },
  bookRowGrid: {
    flexBasis: 320,
    flexGrow: 1,
  },
  setupBookRow: {
    gap: 0,
  },
  bookRowCopy: {
    flex: 1,
  },
  bookRowHeader: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    columnGap: 8,
    rowGap: 6,
    marginTop: 6,
  },
  rowPrompt: {
    fontFamily: fonts.app,
    color: colors.muted,
    fontSize: 13,
    lineHeight: 22,
    fontWeight: "500",
  },
  rowTitle: {
    fontFamily: fonts.app,
    overflow: "hidden",
    borderRadius: 7,
    paddingHorizontal: 10,
    paddingVertical: 2,
    backgroundColor: colors.accentSoft,
    color: colors.ink,
    fontSize: 15,
    lineHeight: 22,
    fontWeight: "600",
  },
  rowAuthor: {
    fontFamily: fonts.app,
    color: colors.accent,
    fontSize: 13,
    lineHeight: 22,
    fontWeight: "600",
  },
  rowWhy: {
    fontFamily: fonts.app,
    marginTop: 8,
    color: colors.muted,
    fontSize: 14,
    lineHeight: 21,
  },
  rowTitleInput: {
    fontFamily: fonts.app,
    marginTop: 10,
    color: colors.ink,
    fontSize: 18,
    lineHeight: 26,
    fontWeight: "600",
    padding: 0,
    overflow: "hidden",
  },
  rowAuthorInput: {
    fontFamily: fonts.app,
    alignSelf: "flex-start",
    marginTop: 10,
    color: colors.accent,
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "600",
    padding: 0,
    overflow: "hidden",
  },
  rowWhyInput: {
    fontFamily: fonts.app,
    marginTop: 10,
    color: colors.muted,
    fontSize: 14,
    lineHeight: 22,
    paddingHorizontal: 0,
    paddingVertical: 4,
    minHeight: 92,
    maxHeight: 132,
    textAlignVertical: "top",
  },
  characterCounter: {
    fontFamily: fonts.app,
    alignSelf: "flex-end",
    marginTop: 6,
    color: colors.muted,
    fontSize: 11,
    lineHeight: 15,
    fontWeight: "500",
  },
  chipRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  relatedChipRow: {
    marginTop: 10,
  },
  chip: {
    fontFamily: fonts.app,
    overflow: "hidden",
    borderRadius: 12,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 7,
    backgroundColor: colors.background,
    borderColor: colors.faint,
    color: colors.muted,
    fontSize: 13,
    fontWeight: "400",
  },
  chipStrong: {
    fontFamily: fonts.app,
    overflow: "hidden",
    borderRadius: 12,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 7,
    backgroundColor: colors.accentSoft,
    borderColor: colors.accent,
    color: colors.accent,
    fontSize: 13,
    fontWeight: "500",
  },
  buttonBase: {
    alignItems: "center",
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  buttonPrimary: {
    backgroundColor: colors.accent,
  },
  buttonSecondary: {
    backgroundColor: colors.background,
    borderWidth: 1,
    borderColor: colors.faint,
  },
  buttonDanger: {
    backgroundColor: colors.accentSoft,
  },
  buttonDisabled: {
    opacity: 0.45,
  },
  buttonPrimaryText: {
    fontFamily: fonts.app,
    color: colors.surface,
    fontWeight: "500",
  },
  buttonSecondaryText: {
    fontFamily: fonts.app,
    color: colors.ink,
    fontWeight: "500",
  },
  buttonDangerText: {
    fontFamily: fonts.app,
    color: colors.accent,
    fontWeight: "500",
  },
  formPanel: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
  segmentQuestion: {
    flexBasis: 280,
    flexGrow: 1,
    gap: 10,
    padding: 14,
    borderRadius: 14,
    backgroundColor: colors.background,
    borderWidth: 1,
    borderColor: colors.faint,
  },
  segmentQuestionWide: {
    flexBasis: "100%",
  },
  questionTitle: {
    fontFamily: fonts.app,
    color: colors.ink,
    fontSize: 15,
    fontWeight: "500",
  },
  segmentRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  pill: {
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 9,
    backgroundColor: colors.background,
    borderWidth: 1,
    borderColor: colors.faint,
  },
  pillActive: {},
  pillText: {
    fontFamily: fonts.app,
    color: colors.muted,
    fontWeight: "400",
  },
  pillTextActive: {
    fontWeight: "600",
  },
  questionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
  },
  wordsColumns: {
    flexDirection: "row",
    gap: 16,
  },
  wordsColumn: {
    flex: 1,
    gap: 8,
  },
  wordsChipStack: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
  },
  wordsRevealActions: {
    marginTop: 14,
    alignItems: "flex-start",
  },
  headerActionSlot: {
    minWidth: 92,
    minHeight: 38,
    alignItems: "flex-end",
  },
  counter: {
    fontFamily: fonts.app,
    color: colors.accent,
    fontWeight: "500",
  },
  readFooterActions: {
    marginTop: 24,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    flexWrap: "wrap",
    gap: 10,
  },
  resultBlockGrid: {
    flexBasis: 320,
    flexGrow: 1,
  },
  resultHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 14,
  },
  resultTitle: {
    fontFamily: fonts.app,
    color: colors.ink,
    fontSize: 16,
    fontWeight: "600",
  },
  resultRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginTop: 12,
  },
  resultLabel: {
    fontFamily: fonts.app,
    width: 104,
    color: colors.muted,
    fontSize: 14,
  },
  resultTraitChip: {
    fontFamily: fonts.app,
    overflow: "hidden",
    width: 104,
    borderRadius: 12,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 7,
    backgroundColor: colors.background,
    borderColor: colors.faint,
    color: colors.muted,
    fontSize: 13,
    fontWeight: "400",
    textAlign: "center",
  },
  resultBarTrack: {
    flex: 1,
    height: 7,
    borderRadius: 999,
    backgroundColor: colors.faint,
    overflow: "hidden",
  },
  resultBarFill: {
    height: "100%",
    borderRadius: 999,
    backgroundColor: colors.accent,
  },
  resultCount: {
    fontFamily: fonts.app,
    width: 22,
    color: colors.ink,
    fontSize: 13,
    fontWeight: "500",
    textAlign: "right",
  },
  modalOverlay: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 24,
    backgroundColor: "rgba(37, 35, 38, 0.42)",
  },
  reportDialog: {
    width: "100%",
    maxWidth: 480,
    gap: 14,
    padding: 20,
    borderRadius: 16,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.faint,
  },
  reportReasonGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  reportReasonButton: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.faint,
    paddingHorizontal: 10,
    paddingVertical: 8,
    backgroundColor: colors.background,
  },
  reportReasonButtonActive: {
    borderColor: colors.accent,
    backgroundColor: colors.accentSoft,
  },
  reportReasonText: {
    fontFamily: fonts.app,
    color: colors.muted,
    fontSize: 13,
    fontWeight: "500",
  },
  reportReasonTextActive: {
    color: colors.accent,
  },
  reportTextInput: {
    minHeight: 104,
    textAlignVertical: "top",
  },
  reportHelperRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
  },
  reportDialogActions: {
    flexDirection: "row",
    justifyContent: "flex-end",
    flexWrap: "wrap",
    gap: 10,
  },
});
